# Site settings
title: LanceMatch
email: hello@lancematch.com
url: "http://lancematch.com"

# Social links
twitter_username: lancematch
twitter_url: "https://twitter.com/LanceMatch"
facebook_url: "https://facebook.com/LanceMatch"

# Build settings
markdown: kramdown
permalink: blog/:title/

assets:
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'Rakefile', 's3_website.yml']
