# Site settings
title: LanceMatch

email: hello@lancematch.com

#baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lancematch.com" # the base hostname & protocol for your site
#url: "http://localhost:4000m" # the base hostname & protocol for your site

twitter_username: jekyllrb
twitter_url: "#"
facebook_url: "#"


# Build settings
markdown: kramdown

permalink: blog/:title/
